"""
File Writer Utility
Writes code generated by the Execution Engine safely to the disk.
"""
from pathlib import Path
from pydantic import BaseModel
from typing import List

from buildmind.ui.terminal import print_info

class FileAction(BaseModel):
    path: str
    content: str
    action: str
    description: str

def write_files(project_dir: Path, files: List[FileAction]) -> None:
    """Safe file writer ensuring paths don't escape project directory."""
    for f in files:
        target_path = (project_dir / f.path).resolve()
        
        # Prevent directory traversal escaping the project root
        if project_dir.resolve() not in target_path.parents:
            print_info(f"Skipping {f.path}: Path escapes project directory.")
            continue
            
        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_text(f.content, encoding="utf-8")
        
        action_verb = "Created" if f.action == "create" else "Updated"
        print_info(f"  [green]{action_verb}[/green] [bold white]{f.path}[/bold white] - {f.description}")
